name: pm-spel-stg

services:
  pm-spel:
    image: plusmin/pm-spel:${PM_STG_VERSION}
    container_name: pm-spel
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "3036:3036"
    volumes:
      - ./nginx-logs:/var/log/nginx
    networks:
      - npm_default
    restart: always

networks:
  npm_default:
    external: true