name: pm-budgetscanner-stg

services:
  pm-budgetscanner:
    image: plusmin/pm-budgetscanner:${PM_STG_VERSION}
    container_name: pm-budgetscanner
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "3036:3036"
    volumes:
      - ./nginx-logs:/var/log/nginx
    networks:
      - npm_default
    restart: always

networks:
  npm_default:
    external: true